name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Make temp directory
        run: |
          cp mkdocs.yml TestPushRepoA-docs/mkdocs.yml
          ls TestPushRepoA-docs/
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: TestPushRepoA-docs/
          target-directory: TestPushRepoA-docs/
          destination-github-username: 'GavinPJK'
          destination-repository-name: 'TestPushRepoEndpoint'
          user-email: kirwangp@tcd.ie
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
